import './routes.js'
import '/imports/scripts/tools'
import '/imports/scripts/config'
import '/imports/components/nav/nav.js'
import '/imports/pages/404/404.js'
import '/imports/pages/home/home.js'
import '/imports/pages/game/game.js'
